import mongoose, { Schema, model } from "mongoose";

const customerAddressSchema = new mongoose.Schema({
  id: Number,
  customer_id: Number,
  first_name: String,
  last_name: String,
  company: String,
  address1: String,
  address2: String,
  city: String,
  province: String,
  country: String,
  zip: String,
  phone: String,
  name: String,
  province_code: String,
  country_code: String,
  country_name: String,
  default: Boolean,
});

const customerSchema = new mongoose.Schema({
  id: Number,
  email: String,
  created_at: Date,
  updated_at: Date,
  first_name: String,
  last_name: String,
  orders_count: Number,
  state: String,
  total_spent: String,
  last_order_id: Number,
  note: String,
  verified_email: Boolean,
  multipass_identifier: String,
  tax_exempt: Boolean,
  phone: String,
  tags: String,
  last_order_name: String,
  currency: String,
  marketing_opt_in_level: String,
  tax_exemptions: [String],
  admin_graphql_api_id: String,
  default_address: customerAddressSchema,
});

const moneySetSchema = new mongoose.Schema({
  shop_money: {
    amount: String,
    currency_code: String,
  },
  presentment_money: {
    amount: String,
    currency_code: String,
  },
});

const lineItemSchema = new mongoose.Schema({
  id: Number,
  variant_id: Number,
  title: String,
  quantity: Number,
  sku: String,
  variant_title: String,
  vendor: String,
  fulfillment_service: String,
  product_id: Number,
  requires_shipping: Boolean,
  taxable: Boolean,
  gift_card: Boolean,
  name: String,
  variant_inventory_management: String,
  properties: [mongoose.Schema.Types.Mixed],
  product_exists: Boolean,
  fulfillable_quantity: Number,
  grams: Number,
  price: Number,
  total_discount: String,
  fulfillment_status: String,
  price_set: moneySetSchema,
  total_discount_set: moneySetSchema,
  discount_allocations: [mongoose.Schema.Types.Mixed],
  duties: [mongoose.Schema.Types.Mixed],
  admin_graphql_api_id: String,
});

const orderSchema = new mongoose.Schema({
  _id: Number,
  id: Number,
  email: String,
  closed_at: Date,
  created_at: Date,
  updated_at: Date,
  number: Number,
  note: String,
  token: String,
  gateway: String,
  test: Boolean,
  total_price: String,
  subtotal_price: String,
  total_weight: Number,
  total_tax: String,
  taxes_included: Boolean,
  currency: String,
  financial_status: String,
  confirmed: Boolean,
  total_discounts: String,
  buyer_accepts_marketing: Boolean,
  name: String,
  referring_site: String,
  landing_site: String,
  cancelled_at: Date,
  cancel_reason: String,
  reference: String,
  user_id: Number,
  location_id: Number,
  source_identifier: String,
  source_url: String,
  device_id: String,
  phone: String,
  customer_locale: String,
  app_id: Number,
  browser_ip: String,
  landing_site_ref: String,
  order_number: Number,
  discount_applications: [mongoose.Schema.Types.Mixed],
  discount_codes: [mongoose.Schema.Types.Mixed],
  note_attributes: [mongoose.Schema.Types.Mixed],
  payment_gateway_names: [String],
  processing_method: String,
  source_name: String,
  fulfillment_status: String,
  tax_lines: [mongoose.Schema.Types.Mixed],
  tags: String,
  contact_email: String,
  order_status_url: String,
  presentment_currency: String,
  total_line_items_price_set: moneySetSchema,
  total_discounts_set: moneySetSchema,
  total_shipping_price_set: moneySetSchema,
  subtotal_price_set: moneySetSchema,
  total_price_set: moneySetSchema,
  total_tax_set: moneySetSchema,
  line_items: [lineItemSchema],
  shipping_lines: [mongoose.Schema.Types.Mixed],
  billing_address: mongoose.Schema.Types.Mixed,
  shipping_address: mongoose.Schema.Types.Mixed,
  fulfillments: [mongoose.Schema.Types.Mixed],
  client_details: mongoose.Schema.Types.Mixed,
  refunds: [mongoose.Schema.Types.Mixed],
  customer: customerSchema,
  total_line_items_price: String,
});

export default model("shopifyOrders", orderSchema, "shopifyOrders");
